spring.datasource:
  url: jdbc:mysql://REMOVED:3306/db4?zeroDateTimeBehavior=convertToNull
  username: REMOVED
  password: REMOVED
  driver-class-name: com.mysql.jdbc.Driver

#allows for case sensitive columns and table names
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
